version: "3.0"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: perntodo
  app:
    depends_on:
      - db
    image: my-pg-node
    ports:
      - 8081:8081
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ayushguptadev1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports: 
      - 5555:80
    depends_on:
      - app
      - db
      


